import Head from "next/head";
import React from "react";
import Link from "next/link";

export default function Home() {

  return (
    <>
      <Head>
        <title>Rick and Searchy! | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section data-testid="test-home">
        <div>
          <h1>Search through 826 characters info in 42 pages</h1>
        </div>
        <Link href="/search">Search!</Link>
      </section>
    </>
  );
}
