import {
  displayFoundResults,
  fetchFromAPI,
} from "@/store/modules/data/actions";
import Head from "next/head";
import { useEffect, useState } from "react";
import { useDispatch } from "react-redux";

export default function Home() {
  const dispatch = useDispatch();
  const [queryType, setQueryType] = useState("name");
  const [query, setQuery] = useState("");

  const handleSearch = async () => {
    const { data }: any = await dispatch(
      fetchFromAPI(`/?${queryType}=${query.toLowerCase()}`)
    );

    dispatch(displayFoundResults(data));
  };

  const handleChange = (e: Event) => {
    const { target } = e;
    if (target) {
      setQueryType((target as HTMLSelectElement).value);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <div>
          <h1>Search through 760 characters info in 42 pages</h1>
        </div>
        <div data-testid="search-form">
          <input
            type="text"
            placeholder="Place your search here!"
            value={query}
            data-testid="search-input"
            onChange={(e) => setQuery(e.target.value)}
          />
          <label htmlFor="searchBy">
            Search By:
            <select
              name="searchBy"
              id="searchBy"
              data-testid="search-select"
              onChange={(e) => handleChange(e as unknown as Event)}
            >
              <option value="name">Name</option>
              <option value="status">Status</option>
              <option value="species">Species</option>
              <option value="gender">Gender</option>
            </select>
          </label>
          <button data-testid="search-go" onClick={() => handleSearch()}>
            Search!
          </button>
        </div>
      </section>
    </>
  );
}
