import CharactersSection from "@/components/CharactersSection";
import { fetchFromAPI, loadFoundResults } from "@/store/modules/data/actions";
import { CharacterState } from "@/store/modules/data/types";
import React, { FormEvent, useState } from "react";
import { useSelector, useDispatch } from "react-redux";
import { apiGet } from "../api/api";
import Head from "next/head";
import Pagination from "@/components/SearchPage/SearchPagination";
import SearchForm from "@/components/SearchPage/SearchForm";
import { CharactersSectionComponent } from "../../styles/search/styles";
import { Subtitle } from "@/components/HomeTitle/styles";

function Search() {
  const data = useSelector<CharacterState, CharacterState>(
    (state) => state
  ).characters;

  const dispatch = useDispatch();
  const [queryType, setQueryType] = useState("name");
  const [query, setQuery] = useState("");

  const handleSearch = async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    await apiGet(
      dispatch,
      fetchFromAPI(`/?${queryType}=${query.toLowerCase()}`),
      loadFoundResults
    );
  };

  const handleChange = (e: Event) => {
    const { target } = e;
    if (target) {
      setQueryType((target as HTMLSelectElement).value);
    }
  };

  return (
    <>
      <Head>
        <title>Rick and Searchy! | Search</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Subtitle>Search for any character!</Subtitle>
      </div>
      <SearchForm
        handleChange={handleChange}
        handleSearch={handleSearch}
        query={query}
        setQuery={setQuery}
      />
      <CharactersSectionComponent>
        {data?.results[0]?.id === 0 ? (
          <Subtitle data-testid="test-catch">Sorry, no valid results were found</Subtitle>
        ) : data?.results?.length !== 0 ? (
          <>
            <CharactersSection charactersData={data?.results} />
            <Pagination data={data} />
          </>
        ) : (
          <Subtitle data-testid="test-search-cta">Search for any character!</Subtitle>
        )}
      </CharactersSectionComponent>
    </>
  );
}

export default Search;
