import CharactersSection from "@/components/CharactersSection";
import { fetchFromAPI, loadFoundResults } from "@/store/modules/data/actions";
import { CharacterState } from "@/store/modules/data/types";
import React, { useState } from "react";
import { useSelector, useDispatch } from "react-redux";
import { apiGet } from "../api/api";
import Head from "next/head";
import Link from "next/link";
import Pagination from "@/components/SearchPagination";

function Search() {
  const data = useSelector<CharacterState, CharacterState>(
    (state) => state
  ).characters;

  const dispatch = useDispatch();
  const [queryType, setQueryType] = useState("name");
  const [query, setQuery] = useState("");

  const handleSearch = async () => {
    await apiGet(
      dispatch,
      fetchFromAPI(`/?${queryType}=${query.toLowerCase()}`),
      loadFoundResults
    );
  };

  const handleChange = (e: Event) => {
    const { target } = e;
    if (target) {
      setQueryType((target as HTMLSelectElement).value);
    }
  };

  return (
    <>
      <Head>
        <title>Rick and Searchy! | Search</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <div data-testid="search-form">
          <input
            type="text"
            placeholder="Place your search here!"
            value={query}
            data-testid="search-input"
            onChange={(e) => setQuery(e.target.value)}
          />
          <label htmlFor="searchBy">
            Search By:
            <select
              name="searchBy"
              id="searchBy"
              data-testid="search-select"
              onChange={(e) => handleChange(e as unknown as Event)}
            >
              <option value="name">Name</option>
              <option value="status">Status</option>
              <option value="species">Species</option>
              <option value="gender">Gender</option>
            </select>
          </label>
          <button data-testid="search-go" onClick={() => handleSearch()}>
            Search!
          </button>
          <Link href="/favourites">Show your favourites!</Link>
        </div>
      </section>
      <section>
        {data?.results?.length !== 0 && (
          <>
            <CharactersSection charactersData={data?.results} />
            <Pagination data={data} />
          </>
        )}
      </section>
    </>
  );
}

export default Search;
